dashbord/urls.py
from django.urls import path
from dashbord.views import index
from . import views
app_name='dashboard'
urlpatterns = [
   path('dashbord', views.index, name='index'),
    path('', views.connect_view, name='connect'),

    
]

eleve/urls.py
from django.urls import path
from dashbord.views import index
from . import views
app_name='eleve'
urlpatterns = [
   path('eleve/', views.eleve, name='index'),
   path('ajouter/', views.ajouter_eleve_view, name='add'),
    path('modifier/', views.modifier_eleve_view, name='edit'),

    
    
]

professeur/urls.py
from django.urls import path
from dashbord.views import index
from . import views
app_name='professeur'
urlpatterns = [
   path('professeur/', views.professeur, name='index'),
   path('ajouterp/', views.ajouter_professeur_view, name='add'),
    path('modifierp/', views.modifier_professeur_view, name='edit'),

    
]

rapport/urls.py
from django.urls import path
from dashbord.views import index
from . import views
app_name='rapport'
urlpatterns = [
   path('rapport/', views.rapport_view, name='rapport'),
    
    
]

src2/urls.py
from django.contrib import admin
from django.urls import path,include
from dashbord.views import index
from eleve.views import eleve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("dashbord.urls")),
    path('html/',include("eleve.urls")),
    path('html/',include("professeur.urls")),
    path('html/',include("utilisateur.urls")),
    path('html/',include("rapport.urls")),
]

utilisateur/urls.py
from django.urls import path
from dashbord.views import index
from . import views
app_name='utilisateur'
urlpatterns = [
   path('utilisateur/', views.utilisateur_view, name='index'),
    path('ajouteru/', views.ajouter_utilisateur_view, name='add'),
    path('modifieru/', views.modifier_utilisateur_view, name='edit'),
    
]

dashbord/models.py
from django.db import models

# Create your models here.

eleve/models.py
from django.db import models

# Create your models here.
class Eleve(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    
class Personne(models.Model):
    first_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    third_name = models.CharField(max_length=30)

    last_name = models.CharField(max_length=30)
    
    

professeur/models.py
from django.db import models

# Create your models here.
class Professeur(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

rapport/models.py
from django.db import models

# Create your models here.

utilisateur/models.py
from django.db import models

# Create your models here.
class Utilisateur(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

eleve/forms.py
    
from django import forms
from .models import Eleve  # Assurez-vous que cela correspond à votre fichier models.py

class EleveForm(forms.Form):
        Nom = forms.CharField(max_length=10)
        Prenom = forms.CharField(max_length=10)
        genre = forms.CharField(max_length=10)
        Matricule = forms.CharField(max_length=10)
        Prenom = forms.CharField(max_length=10)
        Téléphone = forms.CharField(max_length=10)
        ville = forms.CharField(max_length=10)
        date_naissance = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

        CHOICES = [
        ('option1', 'Tle'),
        ('option2', '1ere'),
        ('option3', '2nd'),

        ]
    
        choix = forms.ChoiceField(
            choices=CHOICES,
            widget=forms.Select(attrs={'class': 'form-group'})
        )

professeur/forms.py
    
from django import forms
from .models import Professeur 
class ProfesseurForm(forms.Form):
        Nom = forms.CharField(max_length=10)
        Prenom = forms.CharField(max_length=10)
        genre = forms.CharField(max_length=10)
        Matricule = forms.CharField(max_length=10)
        Prenom = forms.CharField(max_length=10)
        Téléphone = forms.CharField(max_length=10)
        ville = forms.CharField(max_length=10)
        date_naissance = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

        CHOICES = [
        ('option1', 'Sélectionner une matière'),
        ('option2', 'Mathématique'),
        ('option3', 'Français'),

        ]
    
        choix = forms.ChoiceField(
            choices=CHOICES,
            widget=forms.Select(attrs={'class': 'form-group'})
        )

utilisateur/forms.py
    
from django import forms
from .models import Utilisateur 

class UtilisateurForm(forms.Form):
        Pseudo = forms.CharField(max_length=10)
        Mot_de_passe = forms.CharField(max_length=100)
        Confirmer_mot_de_passe = forms.CharField(max_length=10)

dashbord/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "html/dashboard.html")

def connect_view(request):
    return render(request, 'html/connect.html')

eleve/views.py
from django.shortcuts import render
from .forms import EleveForm

# Create your views here.
def eleve(request):
    return render(request, 'html/eleve.html')

def ajouter_eleve_view(request):
    form = EleveForm()
    
    return render(request, 'html/ajouter_eleve.html', {'form': form})

def modifier_eleve_view(request):
    return render(request, 'html/modifier_eleve.html')

professeur/views.py
from django.shortcuts import render
from .forms import ProfesseurForm

# Create your views here.
def professeur(request):
    return render(request, 'html/professeur.html')

def ajouter_professeur_view(request):
    form = ProfesseurForm()

    return render(request, 'html/ajouter_professeur.html', {'form': form})

def modifier_professeur_view(request):
    return render(request, 'html/modifier_professeur.html')

rapport/views.py
from django.shortcuts import render

# Create your views here.
def rapport_view(request):
    return render(request, 'html/rapport.html')

utilisateur/views.py
from django.shortcuts import render
from .forms import  UtilisateurForm

# Create your views here.
def utilisateur_view(request):
    return render(request, 'html/utilisateur.html')

def modifier_utilisateur_view(request):
    return render(request, 'html/modifier_utilisateur.html')

def ajouter_utilisateur_view(request):
    form = UtilisateurForm()
    return render(request, 'html/ajouter_utilisateur.html', {'form': form})

dashbord/templates/html/connect.html
{%load static%}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Page Admin</title>
	
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
	
</head>
	
	<style>
		
	@import url('https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;0,500;1,200;1,300;1,400&display=swap');
	
:root{
--red:#ff3838;
	
}



*{
font-family: 'Nunito', sans-serif;
margin:0; padding:0;
box-sizing: border-box;
text-decoration: none;
}
		
		body{
			display: flex;
			justify-content: center;
			align-items: center;
			min-height: 100vh;
			background-color: cadetblue;
		}
		
		.wrapper{
			width: 420px;
			background:transparent;
			border: 2px solid rgba(255, 255, 255, .2);
			backdrop-filter: blur(20px);
			box-shadow: 0 0 10px rgba(0, 0, 0, .2);
			color: #fff;
			border-radius: 10px;
			padding: 30px 40px;
		}
	
		.wrapper h1{
			font-size: 36px;
			text-align: center;
		}
	
		.wrapper .input-box{
			position: relative;
			width: 100%;
			height: 50%;
			margin: 30px 0;
			
		}
	
		.input-box input{
			width: 100%;
			height: 100%;
			background: transparent;
			border: none;
			outline: none;
			border: 2px solid rgba(255, 255, 255, .2);
			border-radius: 40px;
			font-size: 16px;
			color: #fff;
			padding: 20px 45px 20px 20px;
		}
		
		.input-box input::placeholder{
			color: #fff;
		}
		
		.input-box i{
			position: absolute;
			right: 20px;
			top: 50%;
			transform: translateY(-50%);
			font-size: 20px;
		}
		
		.wrapper .remember-forgot{
			display: flex;
			justify-content: space-between;
			font-size: 14.5px;
			margin: -15px 0 15px;
		}
		
		.remember-forgot label input{
			accent-color: #fff;
			margin-right: 3px;
		}
		
		.remember-forgot a{
			color:#fff;
			text-decoration: none;
		}
		
		.remember-forgot a:hover{
			text-decoration: underline;
		}
		
		.wrapper .btn{
			width: 100%;
			height: 45px;
			background: #fff;
			border: none;
			outline: none;
			border-radius: 40px;
			box-shadow: 0 0 10px rgba(0, 0, 0, .1);
			cursor: pointer;
			font-size: 16px;
			color: #333;
			font-weight: 600;
		}
		
		.logo{
			width: 50%;
			
		}
		
		
		
	</style>

<body>
	
	<div class="wrapper">
	<form action="#" method="post">
		
		<img src="a.png" alt="" class="logo">
		<div class="input-box">
		<input type="text" name="login" placeholder="Identifiant" required>
		<i class="bx bxs-user"></i>
		</div>
		
		<div class="input-box">
		<input type="password" name="password"  placeholder="mot de passe" required>
			<i class="bx bxs-lock-alt"></i>
		</div>
		
		<div class="remember-forgot">
			<label><input type="checkbox">se souvenir de moi</label>
			<a href="{% url 'dashboard:index' %}">Rentrer dans la session</a>
		</div>
		
		
        <button type="submit" class="btn">Valider</button>
		
		
		</form>
	
	
	</div>
</body>
</html>

dashbord/templates/html/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Bienvenue</title>
{% endblock title %}
			
	
	{% block body %}

<!-- A propos des articles ... section starts -->
	
<section class="tous" >
	
	<h1 class="heading">Tableau <span>de bord</span> </h1>
		
		<div class="tablebord">
		
		<div class="tables" id="total1">
		
			
			<h3>Nombre d'élève</h3>
		
			
            <h2>128 100</h2>
		
		</div>
			
		<div class="tables" id="total2">
            <h3>Nombre de professeur</h3>
		
			
            <h2>128 100</h2>
		
		
		</div>
		
			
		<div class="tables" id="total3">
            <h3>Nombre d'utilisateur</h3>
		
            <h2>128 100</h2>
		
		</div>
			
			
		<div class="tables" id="total4">
            <h3>Eleve par genre</h3>
            <canvas id="genderChart"></canvas>
		</div>

			
			</div>
		
	
	
	</section>
</div>



<!--<script src="code.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{%static 'js/graph.js'%}"></script>

{% endblock body %}

eleve/templates/html/ajouter_eleve.html
{% extends 'base.html' %}

{%load static%}

{% block lienCss %}
<link rel="stylesheet" href="{%static 'css/lstyle.css'%}">
{% endblock %}
			
    {% block body %}

<!--Formulaire --> 
	
<section class="grouper">
   
            <div class="form-container">
                <h1>Ajouter un élève</h1>
                <p> <a href="{% url 'eleve:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
                <form>
                    
                    <div class="form-group">
                        
                        <label for="nom"> </label>
                    </div>
                    <div class="form-group">

                        {{ form }}
                    </div>
                    
                      
                    
                    <div class="form-buttons">
                        <button type="button" class="cancel-button">Annuler</button>
                        <button type="submit" class="submit-button">Enregistrer</button>
                    </div>
                </form>
            </div>

        </section>

    </div>

	
	
{% endblock body %}
	
	
	

eleve/templates/html/eleve.html
{% extends 'base.html' %}
{% load static %}
{% block lienCss %}
<!-- custom css file link -->
<link rel="stylesheet" href="{% static 'css/lstyle.css' %}">
{% endblock %}
{% block title %}

<title>Bienvenue</title>

{% endblock title %}

       
{% block body %}
<!-- A propos des articles ... section starts -->
	

<section>

   
    <div class="table_responsive">

        <h1 class="heading">Les <span>élèves</span> </h1>
		<p> <a href="{%url 'eleve:add' %}">Ajouter eleves <i class="fas fa-add"></i></a></p>
        <table>
        
    
    <table align='center' border='2' width='50%'>
          <thead>
        <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Genre</th>
        <th>Classe</th>
        <th>Matricule</th>
        <th>Age</th>
        <th>Telephone</th>
        <th>Ville</th>
        <th>Actions</th>
         </thead>
        </tr>
        
       
           <tr>
            <td>KONAN</td> 
            <td>Junior</td> 
            <td>M</td>
            <td>Licence</td> 
            <td>29087654</td> 
            <td>25</td> 
            <td>0102456789</td>
            <td>Abobo</td>  
          
            
            <td>
             <span class='action_btn'>
                <a href=# style='text-decoration: none' onclick="return confirmation()">Supprimer</a>
            
            
            <a href="{%url 'eleve:edit' %}" style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>

        <tr>
            <td>NYOA</td> 
            <td>Ama</td> 
            <td>F</td>
            <td>Master</td> 
            <td>200514886</td> 
            <td>22</td> 
            <td>0102456789</td>
            <td>Abidjan</td>  
          
            
            <td>
             <span class='action_btn'>
            <a href=# style='text-decoration: none' onclick="return confirmation()">Supprimer</a>
             

            
            <a href="{%url 'eleve:edit' %}" style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>
        
    </table>
            
            
    
        
        
    
      </tbody>
       
      </div>
            
         


</section>

</div>

	<script src={% static 'code.js' %}></script>
	
{% endblock body %}

eleve/templates/html/modifier_eleve.html
{% extends 'base.html' %}

{% load static %}

{% block lienCss %}
<link rel="stylesheet" href="{%static 'css/lstyle.css'%}">
{% endblock %}



{% block body %}
<section class="grouper">
   
    <div class="form-container">
        <h1>Modifier Elève</h1>
        <p> <a href="{% url 'eleve:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
        <form>
            <div class="form-group">
                <label for="nom"></label>
                <input type="text" id="nom" placeholder="nom" name="nom">
            </div>
            <div class="form-group">
                <label for="prenom"></label>
                <input type="text" id="prenom" placeholder="prenom" name="prenom">
            </div>
            <div class="form-group gender-group">
                <label><input type="radio" name="sexe" value="homme"> Homme: </label>
                <label><input type="radio" name="sexe" value="femme"> Femme: </label>
            </div>
            <div class="form-group">
                <label for="matricule"></label>
                <input type="text" id="matricule" placeholder="matricule" name="matricule">
            </div>
            <div class="form-group">
                <label for="date_naissance"> </label>
                <input type="date" id="date_naissance" placeholder="date de naissance" name="date_naissance">
            </div>
            <div class="form-group">
                <label for="classe"></label>
                <select id="classe" name="classe">
                    <option value="">Sélectionner une classe</option>
                    <option value="t1">Tle</option>
                    <option value="1ere">1ère</option>
                    <option value="2nd">2nd</option>
                    <option value="3eme">3ème</option>
                    <option value="4eme">4ème</option>
                    <option value="5eme">5ème</option>
                    <option value="6eme">6ème</option>
                </select>
            </div>
            <div class="form-group">
                <label for="telephone"></label>
                <input type="text" id="telephone" placeholder="telephone" name="telephone">
            </div>
            <div class="form-group">
                <label for="ville"></label>
                <input type="text" id="ville"  placeholder="ville" name="ville">
            </div>
            <div class="form-buttons">
                <button type="button" class="cancel-button">Annuler</button>
                <button type="submit" class="submit-button">Enregistrer</button>
            </div>
        </form>
    </div>

</section>


{% endblock body %}

professeur/templates/html/ajouter_professeur.html
{% extends 'base.html' %}
{%load static%}

    
{% block lienCss %}
<link rel="stylesheet" href="{%static 'css/pstyle.css'%}">
{% endblock %}								




{% block body %}
<!--Formulaire -->

<section class="grouper">
   
            <div class="form-container">
                <h1>Ajouter Professeur</h1>
                <p> <a href="{% url 'professeur:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
                <form>
                    <div class="form-group">
                        {{ form }}

                    </div>
                  
                    <div class="form-buttons">
                        <button type="button" class="cancel-button">Annuler</button>
                        <button type="submit" class="submit-button">Enregistrer</button>
                    </div>
                </form>
            </div>

        </section>

	<script src="code.js"></script>
	{% endblock body %}

professeur/templates/html/modifier_professeur.html
{% extends 'base.html' %}

{%load static%}

    {% block lienCss %}

    <link rel="stylesheet" href="{%static 'css/pstyle.css'%}">
    {% endblock %}							

<!--Formulaire -->
	
{% block body %}
<section class="grouper">
   
            <div class="form-container">
                <h1>Modifier Professeur</h1>
                <p> <a href="{% url 'professeur:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
                <form>
                    <div class="form-group">
                        <label for="nom"></label>
                        <input type="text" id="nom" placeholder="nom" name="nom">
                    </div>
                    <div class="form-group">
                        <label for="prenom"></label>
                        <input type="text" id="prenom" placeholder="prenom" name="prenom">
                    </div>
                    <div class="form-group gender-group">
                        <label><input type="radio" name="sexe" value="homme"> Homme: </label>
                        <label><input type="radio" name="sexe" value="femme"> Femme: </label>
                    </div>
                  
                    <div class="form-group">
                        <label for="date_naissance"> </label>
                        <input type="date" id="date_naissance" placeholder="date de naissance" name="date_naissance">
                    </div>
                    <div class="form-group">
                        <label for="classe"></label>
                        <select id="classe" name="matière">
                            <option value="">Sélectionner une matière</option>
                            <option value="">Math</option>
                            <option value="">Physique</option>
                            <option value="">EPS</option>
                            <option value="">Anglais</option>
                            <option value="">SVT</option>
                            <option value="">Philosophie</option>
                            <option value="">Francais</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="telephone"></label>
                        <input type="text" id="telephone" placeholder="telephone" name="telephone">
                    </div>
                    <div class="form-group">
                        <label for="ville"></label>
                        <input type="text" id="ville"  placeholder="ville" name="ville">
                    </div>
                    <div class="form-buttons">
                        <button type="button" class="cancel-button">Annuler</button>
                        <button type="submit" class="submit-button">Enregistrer</button>
                    </div>
                </form>
            </div>

        </section>

	<script src="code.js"></script>
	{% endblock body %}

professeur/templates/html/professeur.html
{% extends 'base.html' %}

{%load static%}

    
 {% block lienCss %}
    <link rel="stylesheet" href="{%static 'css/pstyle.css'%}">
    {% endblock %}						



	
    {% block body %}
<section>

   
    <div class="table_responsive">

        <h1 class="heading">Les <span>professeurs</span> </h1>
		<p> <a href="{% url 'professeur:add' %}">Ajouter Professeur <i class="fas fa-add"></i></a></p>
        <table>
        
    
    <table align='center' border='2' width='50%'>
          <thead>
        <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Matière</th>
        <th>Vacant</th>
        <th>Age</th>
        <th>Telephone</th>
        <th>Ville</th>
        <th>Actions</th>
         </thead>
        </tr>
        
       
           <tr>
            <td>NDIAYE</td> 
            <td>Gilbert</td> 
            <td>Mathématique</td>
            <td>oui</td> 
            <td>45</td> 
            <td>0123456790</td> 
            <td>Bouaké</td>
           
          
            
            <td>
             <span class='action_btn'>
                <a href=# style='text-decoration: none' onclick="return confirmation()">Supprimer</a>
            
            
            <a href="{% url 'professeur:edit' %}" style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>

        <tr>
            <td>AGBO</td> 
            <td>Alphonse</td> 
            <td>Physique-chimie</td>
            <td>non</td> 
            <td>55</td> 
            <td>0134567890</td> 
            <td>Abidjan</td>
            
            <td>
             <span class='action_btn'>
            <a href=# style='text-decoration: none' onclick="return confirmation()">Supprimer</a>
             

            
            <a href="{% url 'professeur:edit' %}"  style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>
        
    </table>
            
            
    
        
        
    
      </tbody>
       
      </div>
            
         


</section>

</div>


	<script src="code.js"></script>
	
	{% endblock body %}
	
	
	

rapport/templates/html/rapport.html
{% extends 'base.html' %}
{%load static%}

	
{% block lienCss %}
    <link rel="stylesheet" href="{%static 'css/rapport.css'%}">
    {% endblock %}						


    {% block body %}

<section class="oui">


    <div class="container">
        <h1>Rapport</h1>
        <div class="form-container">
            <div class="left-section">
                <label for="select-option">Sélectionner une option:</label>
                <select id="select-option">
                    <option value="eleves">Liste des élèves</option>
                    <option value="professeurs">Liste des professeurs</option>
                    <option value="utilisateurs">Liste des utilisateurs</option>
                </select>
            </div>
            <div class="right-section">
                <button class="btn pdf">Générer format PDF</button>
                <button class="btn excel">Générer format Excel</button>
            </div>
        </div>
    </div>


</section>
	
	<script src="code.js"></script>
    {% endblock body %}
	
	
	
	

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script language="javascript">
        function confirmation(){
            
            return confirm("Attention!!! voulez-vous supprimer cet élève?");
            
        }
        
        
    </script>

   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!-- font awesome cdn link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">


    <link rel="stylesheet" href="{%static 'css/style.css'%}">

    {% block lienCss %} {% endblock %}

    
    
								
    {% block title %}
    <!-- <title>Document</title> -->
    {% endblock title %}

</head>
<body>

    {% include 'sidebar.html' %}
    {% block body %}

    {% endblock body %}

</body>
</html>

templates/sidebar.html
  {%load static%}
  
    <div class="sidebar">
        <div class="logo"></div>
    
        <ul class="menu">
        <li class="active">
    <a href="{% url 'dashboard:index' %}" >
        <i class="fas fa-tachometer-alt"></i>
        <span>Menu de bord</span>
    
    </a>
    
        </li>
    
        <li>
            <a href="{%url 'eleve:index' %}">
                <i class="fas fa-user"></i>
                <span>Eleves</span>
            
    </a>
            
    </li>
        <li>
            <a href="{%url 'professeur:index' %}">
            <i class="fas fa-chart-bar"></i>
            <span>Professeur</span>
                    
            </a>
                    
    </li>
    
        <li>
            <a href="{%url 'utilisateur:index' %}">
            <i class="fas fa-briefcase"></i>
            <span>Utilisateurs</span>
                            
            </a>
                            
    </li>
        <li>
             <a href="{%url 'rapport:rapport' %}">
            <i class="fas fa-question-circle"></i>
             <span>Rapport</span>
                                    
            </a>
                                    
    </li>
            
    
    <li class="logout">
        <a href="{%url 'dashboard:connect' %}">
        <i class="fas fa-sign-out-alt"></i>
        <span>Deconnexion</span>
                                                        
    </a>
                                                        
    </li>                           
                                                
        </ul>
       </div> 
    
       <div class="main--content">
        

utilisateur/templates/html/ajouter_utilisateur.html
{% extends 'base.html' %}

{%load static%}
    
{% block lienCss %}
    <link rel="stylesheet" href="{%static 'css/ustyle.css'%}">
    {% endblock %}						


    {% block body %}
<!--Formulaire -->
	
<section class="grouper">
   
            <div class="form-container">
                <h1>Ajouter un utilisateur</h1>
                <p> <a href="{% url 'utilisateur:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
                <form>
                    <div class="form-group">
                        {{ form }}
                    </div>
                   
                    <div class="form-buttons">
                        <button type="button" class="cancel-button">Annuler</button>
                        <button type="submit" class="submit-button">Enregistrer</button>
                    </div>
                </form>
            </div>

        </section>

	<script src="code.js"></script>
	
	{% endblock body %}
	
	
	

utilisateur/templates/html/modifier_utilisateur.html
{% extends 'base.html' %}
{%load static%}


{% block lienCss %}
    <link rel="stylesheet" href="{%static 'css/ustyle.css'%}">
{% endblock %}							




{% block body %}

<!--Formulaire -->
	
<section class="grouper">
   
            <div class="form-container">
                <h1>Modifier un utilisateur</h1>
                <p> <a href="{% url 'utilisateur:index' %}">Retour <i class="	fas fa-arrow-circle-right"></i></a></p>
                <form>
                    <div class="form-group">
                        <label for="pseudo"> </label>
                        <input type="text" id="nom" placeholder="admin" name="pseudo">
                    </div>
                    <div class="form-group">
                        <label for="mot de passe"> </label>
                        <input type="text" id="prenom" placeholder="ancien mot de passe" name="ancien">
                    </div>

                    <div class="form-group">
                        <label for="mot de passe"> </label>
                        <input type="text" id="prenom" placeholder=" nouveau mot de passe" name="nouveau">
                    </div>
                   
                    <div class="form-group">
                        <label for="confirmer"> </label>
                        <input type="text" id="telephone" placeholder="confirmer mot de passe" name="confirm">
                    </div>
                   
                    <div class="form-buttons">
                        <button type="button" class="cancel-button">Annuler</button>
                        <button type="submit" class="submit-button">Enregistrer</button>
                    </div>
                </form>
            </div>

        </section>


	<script src="code.js"></script>
	
    {% endblock body %}

utilisateur/templates/html/utilisateur.html
{% extends 'base.html' %}
{%load static%}

            
{% block lienCss %}
    <link rel="stylesheet" href="{%static 'css/ustyle.css'%}">
    {% endblock %}							

    {% block body %}
	

<section>

   
    <div class="table_responsive">

        <h1 class="heading">Les <span>Utilisateurs</span> </h1>
		<p> <a href="{% url 'utilisateur:add' %}">Ajouter utilisateur <i class="fas fa-add"></i></a></p>
        <table>
        
    
    <table align='center' border='2' width='50%'>
          <thead>
        <tr>
        <th>Pseudo</th>
        <th>Date de creation</th>
        <th>Actions</th>
         </thead>
        </tr>
        
       
           <tr>
            <td>admin</td> 
            <td>18/08/2024</td> 
           
          
            
            <td>
             
                <span class='action_btn'>
            <a href="{% url 'utilisateur:edit' %}" style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>

        <tr>
            <td>user2</td> 
            <td>13/08/2024</td> 
            
            <td>
                <span class='action_btn'>
            <a href="{% url 'utilisateur:edit' %}" style='text-decoration: none'>Modifier</a>
            </span>
            </td>
        </tr>
        
    </table>
            
            
    
        
        
    
      </tbody>
       
      </div>
            
         


</section>

	<script src="code.js"></script>
	
    {% endblock body %}
	
	
	